package namegen

// Word lists derived from the moby project naming convention.
// All words are lowercase alphabetic only (no hyphens, digits, or special chars).
// The longest adjective + hyphen + longest noun must not exceed 63 characters
// to satisfy RFC 1123 label constraints.

var adjectives = []string{
	"admiring", "adoring", "agitated", "amazing", "angry",
	"awesome", "beautiful", "blissful", "bold", "boring",
	"brave", "busy", "charming", "clever", "compassionate",
	"competent", "condescending", "confident", "cool", "cranky",
	"crazy", "dazzling", "determined", "distracted", "dreamy",
	"eager", "ecstatic", "elastic", "elated", "elegant",
	"eloquent", "epic", "exciting", "fervent", "festive",
	"flamboyant", "focused", "friendly", "frosty", "funny",
	"gallant", "gifted", "goofy", "gracious", "great",
	"happy", "hardcore", "heuristic", "hopeful", "hungry",
	"infallible", "inspiring", "intelligent", "interesting", "jolly",
	"jovial", "keen", "kind", "laughing", "loving",
	"lucid", "magical", "modest", "musing", "mystifying",
	"naughty", "nervous", "nice", "nifty", "nostalgic",
	"objective", "optimistic", "peaceful", "pedantic", "pensive",
	"practical", "priceless", "quirky", "quizzical", "radiant",
	"recursing", "relaxed", "reverent", "romantic", "sad",
	"serene", "sharp", "silly", "sleepy", "stoic",
	"strange", "stupefied", "suspicious", "sweet", "tender",
	"thirsty", "trusting", "unruffled", "upbeat", "vibrant",
	"vigilant", "vigorous", "wizardly", "wonderful", "xenodochial",
	"youthful", "zealous", "zen",
}

var nouns = []string{
	"albattani", "allen", "almeida", "archimedes", "ardinghelli",
	"aryabhata", "austin", "babbage", "banach", "bardeen",
	"bartik", "bassi", "beaver", "bell", "benz",
	"bhabha", "bhaskara", "blackburn", "blackwell", "bohr",
	"booth", "borg", "bose", "boyd", "brahmagupta",
	"brattain", "brown", "burnell", "cannon", "carson",
	"cartwright", "cerf", "chandrasekhar", "chatelet", "clarke",
	"cohen", "colden", "cori", "cray", "curie",
	"darwin", "davinci", "dewdney", "dhawan", "dirac",
	"driscoll", "dubinsky", "easley", "edison", "einstein",
	"elbakyan", "elgamal", "elion", "ellis", "engelbart",
	"euclid", "euler", "faraday", "feistel", "fermat",
	"fermi", "feynman", "franklin", "gagarin", "galileo",
	"galois", "ganguly", "gates", "gauss", "germain",
	"goldberg", "goldstine", "goldwasser", "golick", "goodall",
	"gould", "greider", "grothendieck", "haibt", "hamilton",
	"haslett", "hawking", "heisenberg", "hellman", "hermann",
	"herschel", "hertz", "heyrovsky", "hodgkin", "hofstadter",
	"hoover", "hopper", "hugle", "hypatia", "ishizaka",
	"jackson", "jang", "jennings", "jepsen", "johnson",
	"joliot", "jones", "kalam", "kapitsa", "kare",
	"keldysh", "keller", "kepler", "khorana", "kilby",
	"kirch", "knuth", "kowalevski", "lalande", "lamarr",
	"lamport", "leakey", "leavitt", "lederberg", "lehmann",
	"lewin", "lichterman", "liskov", "lovelace", "lumiere",
	"mahavira", "margulis", "matsumoto", "maxwell", "mayer",
	"mccarthy", "mcclintock", "mclean", "mcnulty", "mendel",
	"mendeleev", "meitner", "meninsky", "merkle", "mirzakhani",
	"montalcini", "moore", "morse", "murdock", "moser",
	"napier", "nash", "neumann", "newton", "nightingale",
	"nobel", "noether", "northcutt", "noyce", "panini",
	"pare", "pascal", "pasteur", "payne", "perlman",
	"pike", "poincare", "poitras", "proskuriakova", "ptolemy",
	"raman", "ramanujan", "ride", "ritchie", "robinson",
	"roentgen", "rosalind", "rubin", "saha", "sammet",
	"sanderson", "satoshi", "shamir", "shannon", "shaw",
	"shirley", "shockley", "shtern", "sinoussi", "snyder",
	"solomon", "spence", "stonebraker", "sutherland", "swanson",
	"swartz", "swirles", "taussig", "tereshkova", "tesla",
	"tharp", "thompson", "torvalds", "tu", "turing",
	"varahamihira", "vaughan", "villani", "visvesvaraya", "volhard",
	"wescoff", "wilbur", "wiles", "williams", "wilson",
	"wing", "wozniak", "wright", "wu", "yalow",
	"yonath", "zhukovsky",
}
