apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-api
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane-operator
imagePullSecrets:
  - name: ghcr-pull
